### ISSUE TITLE
Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by ro0gr** [cibernox/ember-cli-yuidoc#50]
I [get](https://github.com/ember-learn/ember-cli-addon-docs/issues/106#issuecomment-373826929) this error with a fresh master of "ember-cli-addon".

An error from _"tmp\docs_generator-output_path-VlZqdJPb.tmp"_: 
```
Cannot read property 'push' of undefined
  - name: Error
  - nodeAnnotation: DocsGenerator
  - nodeName: DocsGenerator
  - originalErrorMessage: Cannot read property 'push' of undefined
  - stack: TypeError: Cannot read property 'push' of undefined
    at generateYuiDocJsonApi (C:\Users\kudgo\workspace\ember-cli-addon-docs\node_modules\ember-cli-addon-docs-yuidoc\lib\preprocessors\generate-yuidoc-jsonapi.js:76:22)
    at DocsGenerator.build (C:\Users\kudgo\workspace\ember-cli-addon-docs\node_modules\ember-cli-addon-docs-yuidoc\lib\broccoli\generator.js:23:16)
    at C:\Users\kudgo\workspace\ember-cli-addon-docs\node_modules\broccoli-caching-writer\index.js:149:21
    at tryCatch (C:\Users\kudgo\workspace\ember-cli-addon-docs\node_modules\rsvp\dist\rsvp.js:525:12)
    at invokeCallback (C:\Users\kudgo\workspace\ember-cli-addon-docs\node_modules\rsvp\dist\rsvp.js:538:13)
    at publish (C:\Users\kudgo\workspace\ember-cli-addon-docs\node_modules\rsvp\dist\rsvp.js:508:7)
    at flush (C:\Users\kudgo\workspace\ember-cli-addon-docs\node_modules\rsvp\dist\rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

=================================================================================
```

**Comment by ro0gr** [comment]
oops different repo. Sorry.
